### PR TITLE
Implementation of keyring secrets handler

### PR DESCRIPTION
**Pull request by ross**
This turned out pretty cool. I'll probably switch over to using it to for secrets while doing local dev (OSX keychain backend, default on mac.)

/cc https://github.com/octodns/octodns/pull/1140
/cc @octodns/review FYI &amp; and for 💭

### CODE REVIEW

**Comment by ross** [comment]
CI will fail until https://github.com/octodns/octodns/pull/1140 lands and is released.

**Comment by yzguy** [comment]
Neat, I could imagine a lot of cool secret handlers in the future.

So let's say for Mac, I open Keychain Access, if I have `keyring/octodns/AWS_SECRET_ACCESS_KEY`..
Is it a octodns custom keychain with a password named "AWS_SECRET_ACCESS_KEY" in it?

I tried to do just below after creating a password named AWS_SECRET_ACCESS_KEY

```python
import keyring
keyring.get_password("octodns", "AWS_SECRET_ACCESS_KEY")
```

Nothing was returned, which admittedly I don't ever use keychain so I'm very likely not doing something right.

**Comment by ross** [comment]
Easiest thing to do is a `set_password` first. Then you can open up the keychain app and search for octodns to find it and see how it's stored and what bits go where.

I assume it's different for different secret back ends. There's a lot of 3rd party ones too, e.g. 1password.

**Comment by yzguy** [comment]
Ah I should have thought of that :D
Just did it and I see how it's doing it, easy enough.

Handler is simple enough to me, but definitely will be nice change up from environment variables.

👍 from me

**Comment by istr** [comment]
@ross that is a great move! I also have one or two secrets handlers in mind. :slightly_smiling_face:

**Comment by ross** [comment]
Going to ship this initial version and the cut a release so it's out there. It's brand new so that should be fine 😁

**Pull request merged**
